services:
  - type: web
    name: corditur-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        fromFile: true # Esto significa que leer√° la variable desde un archivo .env en Render
      - key: JWT_SECRET
        fromFile: true